@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "a:AddCommand" as AddCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("add n/John Doe p/98765432 ...")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("add n/John ...")
activate AddressBookParser

create AddCommandParser
AddressBookParser -> AddCommandParser : new AddCommandParser()
activate AddCommandParser
AddCommandParser --> AddressBookParser : return AddCommandParser
deactivate AddCommandParser

AddressBookParser -> AddCommandParser : parse("n/John ...")
activate AddCommandParser

create AddCommand
AddCommandParser -> AddCommand : new AddCommand(person)
activate AddCommand
AddCommand --> AddCommandParser : return AddCommand
deactivate AddCommand

AddCommandParser --> AddressBookParser : return AddCommand
deactivate AddCommandParser
destroy AddCommandParser

AddressBookParser --> LogicManager : return AddCommand
deactivate AddressBookParser

LogicManager -> AddCommand : execute(model)
activate AddCommand

AddCommand -> Model : hasPerson(toAdd)
activate Model
Model --> AddCommand : false
deactivate Model

AddCommand -> Model : addPerson(toAdd)
AddCommand -> Model : commit()

create CommandResult
AddCommand -> CommandResult : new CommandResult("New person added: John Doe")
activate CommandResult
CommandResult --> AddCommand : return CommandResult
deactivate CommandResult

AddCommand --> LogicManager : return CommandResult
deactivate AddCommand

[<-- LogicManager : return CommandResult
deactivate LogicManager
@enduml
