@startuml
!include style.puml
skinparam ArrowFontStyle plain



participant "root:Region" as Region UI_COLOR_T3

box Ui UI_COLOR_T1
participant ":CommandHistoryMenu" as CommandHistoryMenu UI_COLOR
participant ":CommandHistoryMenuController" as CommandHistoryMenuController UI_COLOR
end box

participant ":ListView" as ListView UI_COLOR_T3
participant ":MultipleSelectionModel" as MultipleSelectionModel UI_COLOR_T3

CommandHistoryMenu -> Region : setVisible(true)
Region --> CommandHistoryMenu

[-> CommandHistoryMenu : handleMovementUp()
activate CommandHistoryMenu

CommandHistoryMenu -> CommandHistoryMenuController : moveUp() selected index
activate CommandHistoryMenuController

CommandHistoryMenuController --> CommandHistoryMenu
deactivate CommandHistoryMenuController

CommandHistoryMenu -> CommandHistoryMenuController : getCommandSelectionIndex()
activate CommandHistoryMenuController

CommandHistoryMenuController --> CommandHistoryMenu : Optional index
deactivate CommandHistoryMenuController

opt UI_COLOR_T1 Index is present
  CommandHistoryMenu -> ListView : getSelectionModel()
  activate ListView

  ListView --> CommandHistoryMenu : return MultipleSelectionModel
  deactivate ListView

  CommandHistoryMenu -> MultipleSelectionModel : select(index)
  note right
  Highlights the element
  at the selected index
  of the ListView
  end note
end

[<-- CommandHistoryMenu
deactivate CommandHistoryMenu

@enduml
