@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant "r:ListCommand" as ListCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute("list")
activate LogicManager

LogicManager -> ListCommand : execute(m)
activate ListCommand


ListCommand -> Model : updateFilteredPersonList()
activate Model

Model --> ListCommand
deactivate Model

ListCommand -> Model : commit()
activate Model

Model --> ListCommand
deactivate Model

create CommandResult
ListCommand -> CommandResult : new CommandResult("Listed all persons")
activate CommandResult

CommandResult --> ListCommand : return CommandResult
deactivate CommandResult

ListCommand --> LogicManager : return CommandResult
deactivate ListCommand

[<--LogicManager : return CommandResult
deactivate LogicManager
@enduml
